apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: hello-ctr
      image: docker.io/hello-world:latest
      ports:
        - containerPort: 8080
  restartPolicy: Never
