apiVersion: v1
kind: Pod
metadata:
  name: apache-busybox-pod
  labels:
    app: multi-container-pod
spec:
  containers:
    - name: busybox
      image: busybox:1.37.0
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
    - name: httpd
      image: httpd:2.4.62
      ports:
        - containerPort: 80
