apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox-pod
spec:
  containers:
    - name: busybox-container
      image: busybox:1.37.0
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
